runtime: nodejs
env: flex
# service: ci-webserver

# Instead of letting Google scale the app, force only 1 instance by hand
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
